[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  colorscheme onedark
'''

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/gitgutter.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
source ~/.config/nvim/plugins/anzu.vim
'''
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
#repo = 'altercation/vim-colors-solarized'
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
source ~/.config/nvim/plugins/nerdtree.vim
'''
[[plugins]]	# toml syntax
repo = 'mattn/sonictemplate-vim'
hook_add = '''
source ~/.config/nvim/plugins/sonictemplate.vim
'''

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-airline/vim-airline'

